spring.application.name=ad_board
spring.datasource.url=jdbc:postgresql://localhost:5432/ad_board_db
spring.datasource.username=ad_board_admin
spring.datasource.password=Admin
spring.datasource.driver-class-name=org.postgresql.Driver