spring.application.name=ad_board
spring.datasource.url=jdbc:postgresql://localhost:5432/ad_board_db
spring.datasource.username=ad_board_admin
spring.datasource.password=Admin
spring.datasource.driver-class-name=org.postgresql.Driver
#jwt
jwt.secret=lVfj123lwFhg5482iuRxs4324aA145dlhf23gGH6jdGhUcRa642
jwt.lifetime=2592000000